apiVersion: v1
kind: Service
metadata:
  name: simple-service
spec:
  selector:
    app: simple-pod
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  labels:
    app: simple-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-pod
  template:
    metadata:
      labels:
        app: simple-pod
    spec:
      containers:
        - name: simple-pod
          image: hello-world-alex-example-9999
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
            requests:
              memory: '64Mi'
              cpu: '250m'
          readinessProbe:
            httpGet:
              path: /readiness
              port: 5000
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /readiness
              port: 5000
            initialDelaySeconds: 2
            periodSeconds: 5
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-service
                port:
                  number: 5000
---
